### ISSUE TITLE
stdout not working in notebook

### ISSUE THREAD

**Issue by pya** [pya/mochi-kernel#1]
Platform: Mac OSX 10.9.5
Versions: Python 3.4.2, IPython 3.0.0-dev, mochi-kernel 0.1.0, mochi 0.1.4
While printing works with the console and qtconsole, it does not work in the notebook.
Only the return value ‚None‘ is displayed. stdout is IPython.kernel.zmq.iostream.OutStream for all three variants (console, qtconsole, and notebook). Only notebook does not work. Same for sys.stdout.write().

**Comment by Carreau** [comment]
Should be fixed now, if you reinstall you should get syntax highlighting. 

This is still not perfect though.

**Comment by Carreau** [comment]
Oh, and it should create, the `~/.ipython/mochi/kernel.json` as `setup.py install` time.

**Comment by pya** [comment]
Works like a charm.

**Comment by Carreau** [comment]
Great, the output interleaved with `None` is due to mochi itself. 
I've also added you as collab on this repo. Feel free to push simple fixes. 

Do you have a PyPi username ? I can also make you admin there if you like.
